http:
  routers:
    frontend-socket-router:
      entryPoints:
        - websecure
      rule: (Host(`tailoredpsychology.com.au`) || Host(`www.tailoredpsychology.com.au`)) && PathPrefix(`/socket.io`)
      priority: 100
      service: backend-service
      tls:
        certResolver: letsencrypt

    frontend-router:
      entryPoints:
        - websecure
      rule: Host(`tailoredpsychology.com.au`) || Host(`www.tailoredpsychology.com.au`)
      priority: 1
      service: frontend-service
      tls:
        certResolver: letsencrypt

    backend-router:
      entryPoints:
        - websecure
      rule: Host(`api.tailoredpsychology.com.au`)
      service: backend-service
      tls:
        certResolver: letsencrypt

  services:
    frontend-service:
      loadBalancer:
        servers:
          - url: http://frontend:3000

    backend-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://backend:3001
