import { buildInvoicePdf } from "./invoice-pdf.util"

describe("buildInvoicePdf", () => {
  it("returns a valid PDF buffer with invoice content", () => {
    const buffer = buildInvoicePdf({
      invoiceId: "INV-1042",
      issuedDate: "1 June 2026",
      amountLabel: "$220.00",
      status: "Paid",
    })

    const text = buffer.toString("utf8")
    expect(text.startsWith("%PDF-1.4")).toBe(true)
    expect(text).toContain("Tailored Psychology")
    expect(text).toContain("TAX INVOICE / RECEIPT")
    expect(text).toContain("INV-1042")
    expect(text).toContain("Psychology Session / Consultation")
    expect(text).toContain("Generated by the patient portal")
    expect(text).toContain("Rebate eligibility is determined by Medicare and your referrer")
  })

  it("renders payment status in uppercase", () => {
    const buffer = buildInvoicePdf({
      invoiceId: "INV-0001",
      issuedDate: "1 June 2026",
      amountLabel: "$220.00",
      status: "pending",
    })

    expect(buffer.toString("utf8")).toContain("PENDING")
  })
})
